import { v4 as uuid } from 'uuid';

export const annotations = [
  {
    id: uuid(),
    title: 'Sustainable crypto',
    subTitle: '#blockchain #green  #harddisk',
    description:
      'Blockchain and cryptocurrencies were one of the biggest hits in 2020, but critics voiced concerns about sustainability factors. That’s why cryptoes with green mining characteristics could be the next big things in 2021.',
    x: 100,
    y: 28,
    dx: 280,
    dy: 30,
    section: 0,
    tickers: ['XCH', 'SLR'],
  },
  {
    id: uuid(),
    title: 'Vertical and Floating Farms',
    subTitle: ' #hydroponics #microgreens',
    description:
      'Each year, we watch as more and more Earth is claimed by cities and towns. Trees are leveled to make way for villages. Hills are leveled to make way for roads. The soil is upended so that we can uncover precious rocks and minerals. Fortunately, there are a number of individuals who are trying to slow this process. Although they cannot restore dead habitats or solve our deforestation crisis with new, technological innovations, they can (perhaps) make things a little better.',
    x: 130,
    y: 45,
    dx: 300,
    dy: -20,
    section: 0,
    tickers: ['APPH', 'CUBXF', 'HYFM'],
  },
  // {
  //   id: uuid(),
  //   title: 'Ocean cooling',
  //   subTitle: '#climate #reef #aquafarming',
  //   tickers: ['CPWR'],
  //   x: 130,
  //   y: 45,
  //   dx: 280,
  //   dy: -20,
  //   section: 0,
  // },
  {
    id: uuid(),
    title: 'Ocean cooling',
    subTitle: '#climate #reef #aquafarming',
    tickers: ['CPWR'],
    x: 210,
    y: 140,
    dx: 290,
    dy: 50,
    section: 0,
  },
  {
    id: uuid(),
    title: 'Vaccines',
    subTitle: '#covid #mRNS #immunity',
    tickers: ['BTNX', 'MRNA', 'ABBV'],
    x: 308,
    y: 390,
    dx: -100,
    dy: 50,
    section: 1,
  },
  // {
  //   id: uuid(),
  //   title: 'Lorem Ipsum',
  //   subTitle: 'Dolor sit amet',
  //   x: 368,
  //   y: 410,
  //   dx: 250,
  //   dy: 50,
  //   section: 1,
  // },
  {
    id: uuid(),
    title: 'Consumer Drones',
    subTitle: '#selfie #aerial',
    x: 470,
    y: 115,
    dx: -100,
    dy: -50,
    section: 2,
  },
  {
    id: uuid(),
    title: 'Low Budget Airlines',
    subTitle: '#onboard #travel',
    x: 570,
    y: 82,
    dx: 250,
    dy: 50,
    section: 2,
  },
  {
    id: uuid(),
    title: 'Crypto',
    subTitle: '#blockchain #defi #mining',
    tickers: ['BTC', 'ETH'],
    x: 870,
    y: 135,
    dx: -100,
    dy: -50,
    section: 3,
  },
  {
    id: uuid(),
    title: 'Electric Vehicles',
    subTitle: '#battery #gogreen #zeroemission',
    tickers: ['CCIV', 'LI', 'XPEV'],
    x: 730,
    y: 110,
    dx: -100,
    dy: 50,
    section: 3,
  },
  {
    id: uuid(),
    title: 'Digital banking',
    subTitle: '#realtime #virtualcards #microloans',
    tickers: ['SQ', 'LMND', 'ALLY'],
    x: 930,
    y: 144,
    dx: -100,
    dy: -130,
    section: 3,
  },
  {
    id: uuid(),
    title: '3D printing',
    subTitle: '#prototyping #SLS #stereolithography',
    tickers: ['PRLB', 'XONE', 'NNDM'],
    x: 1050,
    y: 158,
    dx: -100,
    dy: 150,
    section: 4,
  },
  {
    id: uuid(),
    title: 'Virtual Reality',
    subTitle: '#simulation #AR #metaverse',
    tickers: ['QCOM', 'LITE'],
    x: 1150,
    y: 165,
    dx: -100,
    dy: -60,
    section: 4,
  },
];
